/* Optional: regional / local councils served to the Record Incident form via /api/councils.
   Run once on the target database after schema.sql. Safe to re-run: seeds only when table is empty. */

IF SCHEMA_ID('rifiiorg') IS NULL
BEGIN
    EXEC('CREATE SCHEMA rifiiorg');
END;

IF OBJECT_ID('rifiiorg.Council_Lookup', 'U') IS NULL
BEGIN
    CREATE TABLE [rifiiorg].[Council_Lookup]
    (
        Id INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_Council_Lookup PRIMARY KEY,
        RegionalCouncil NVARCHAR(150) NOT NULL,
        LocalCouncil NVARCHAR(150) NOT NULL
    );

    CREATE NONCLUSTERED INDEX IX_Council_Lookup_Regional
        ON [rifiiorg].[Council_Lookup] (RegionalCouncil);
END;

IF NOT EXISTS (SELECT 1 FROM [rifiiorg].[Council_Lookup])
BEGIN
    INSERT INTO [rifiiorg].[Council_Lookup] (RegionalCouncil, LocalCouncil) VALUES
    (N'CENTRAL REGION', N'HAFIZABAD'),
    (N'CENTRAL REGION', N'LAHORE'),
    (N'CENTRAL REGION', N'MULTAN & BAHAWALPUR'),
    (N'CENTRAL REGION', N'PESHAWAR'),
    (N'CENTRAL REGION', N'RAWALPINDI'),
    (N'CENTRAL REGION', N'SARGODHA'),
    (N'GILGIT REGION', N'GILGIT'),
    (N'GILGIT REGION', N'SKARDU'),
    (N'GILGIT REGION', N'DSOR'),
    (N'GUPIS & YASIN REGION', N'GHOLAGHMULI'),
    (N'GUPIS & YASIN REGION', N'GUPIS'),
    (N'GUPIS & YASIN REGION', N'PHUNDER'),
    (N'GUPIS & YASIN REGION', N'PINGAL'),
    (N'GUPIS & YASIN REGION', N'SILGAN'),
    (N'GUPIS & YASIN REGION', N'SULTANABAD'),
    (N'GUPIS & YASIN REGION', N'THOI'),
    (N'GUPIS & YASIN REGION', N'YASIN'),
    (N'HUNZA REGION', N'ALTIT & KARIMABAD'),
    (N'HUNZA REGION', N'ALYABAD & HYDERABAD'),
    (N'HUNZA REGION', N'CHUPERSON'),
    (N'HUNZA REGION', N'GUJAL BALA'),
    (N'HUNZA REGION', N'GULMIT'),
    (N'HUNZA REGION', N'NASIRABAD'),
    (N'HUNZA REGION', N'SHIMSHAL'),
    (N'ISHKOMAN & PUNIYAL REGION', N'CHATOORKHAND'),
    (N'ISHKOMAN & PUNIYAL REGION', N'DAMAS'),
    (N'ISHKOMAN & PUNIYAL REGION', N'GAHKUCH'),
    (N'ISHKOMAN & PUNIYAL REGION', N'ISHKOMAN'),
    (N'ISHKOMAN & PUNIYAL REGION', N'SHERQUILLA'),
    (N'ISHKOMAN & PUNIYAL REGION', N'SINGAL'),
    (N'ISHKOMAN & PUNIYAL REGION', N'IMMIT'),
    (N'LOWER CHITRAL REGION', N'ARKARI'),
    (N'LOWER CHITRAL REGION', N'CHITRAL TOWN'),
    (N'LOWER CHITRAL REGION', N'GARAMCHASHMA'),
    (N'LOWER CHITRAL REGION', N'MADAKLASHT'),
    (N'LOWER CHITRAL REGION', N'PARABEG'),
    (N'LOWER CHITRAL REGION', N'SHOGHORE'),
    (N'LOWER CHITRAL REGION', N'SUSUM'),
    (N'SOUTHERN REGION', N'GARDEN'),
    (N'SOUTHERN REGION', N'GULSHAN'),
    (N'SOUTHERN REGION', N'HYDERABAD'),
    (N'SOUTHERN REGION', N'KARIMABAD'),
    (N'SOUTHERN REGION', N'KHARADAR'),
    (N'SOUTHERN REGION', N'TANDO TUREL'),
    (N'SOUTHERN REGION', N'THATTA & SHAH BUNDER'),
    (N'UPPER CHITRAL REGION', N'BANG'),
    (N'UPPER CHITRAL REGION', N'BOONI'),
    (N'UPPER CHITRAL REGION', N'BREP'),
    (N'UPPER CHITRAL REGION', N'KHOT'),
    (N'UPPER CHITRAL REGION', N'MASTUJ'),
    (N'UPPER CHITRAL REGION', N'MULKHOW'),
    (N'UPPER CHITRAL REGION', N'YARKHOON LASHT'),
    (N'UPPER CHITRAL REGION', N'RECH'),
    (N'UPPER CHITRAL REGION', N'LASPUR'),
    (N'UPPER CHITRAL REGION', N'CENTER TORKHOW');
END;
